config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'

   root 'items#index'
   get 'login/login' =>'login#login',as: :login_page
   post 'login/logincheck' => 'login#logincheck' ,as: :login_logincheck
   get 'login/logout' => 'login#logout',as: :signout
   
   
   get 'users/new' => 'users#new', as: :signup
   post 'users/create' => 'users#create', as: :users
   get 'users' => 'users#index',as: :all_users
   get 'users/pastorders' => 'users#pastorders',as: :pastorders
   get 'users/missedorders' => 'users#missedorders',as: :missedorders
   
   get 'admins/new' => 'admins#new', as: :adminsignup
   post 'admins/create' => 'admins#create', as: :admins
   get 'admins/orders' => 'admins#orders', as: :orders
   get 'admins/details/:id' => 'admins#details',as: :details

   get 'admins/delete_order/:id'=> 'admins#delete_order',as: :delete_order

   post 'admins/order_status_update' => 'admins#order_status_update',as: :order_status_update
   
    get 'categories/index' => 'categories#index',as: :allcategories
    get 'categories/new' => 'categories#new',as: :newcategory
    post 'categories/create' => 'categories#create',as: :categories
    get 'categories/destroy/:id'=> 'categories#destroy',as: :deletecategory
    get 'categories/:id' => 'categories#show' , as: :show_category
    resources :items
    get 'items/unavailable/:id'=> 'items#unavailable',as: :unavailableitem 
      
    resources :item_orders
    get 'cart/index' => "cart#index", as: :cart
    get 'cart/clear_cart' => "cart#clear_cart",as: :clear_cart
    

    resources :transactions ,only: [:new,:create]

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :items, dependent: :destroy
validates :name, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, :description, :price, :image, :category_id ,presence: true
  has_many :item_orders,dependent: :destroy
  has_many :orders,:through => :Item,dependent: :destroy
  belongs_to :category
end

app/models/item_order.rb
class ItemOrder < ActiveRecord::Base
  belongs_to :item
  belongs_to :order
end

app/models/missed_order.rb
class MissedOrder < ActiveRecord::Base
  has_one :order,dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :item_orders,dependent: :destroy
  has_many :items,:through => :item_orders,dependent: :destroy
  belongs_to :user
  belongs_to :status
end

app/models/status.rb
class Status < ActiveRecord::Base
 has_many :orders,dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
 has_secure_password
 validates :password, confirmation: true
 validates :password_confirmation, presence: true
 validates :full_name, :email,presence: true
 validates :email, uniqueness: true
 has_many :orders,dependent: :destroy
 def has_payment_info?
  self.braintree_customer_id
 end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
 
 def index
 	@item_orders =  current_order.item_orders
 	if @item_orders.count > 0
 	 @sum = sum(current_order.id)
  end
 end
 def clear_cart
 	 session[:order_id] = nil
 end

 def add_to_cart
 raise params.inspect
 end
 def discard
  raise params.inspect
 end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :auth_admin, only: [:new,:create,:edit,:update,:destroy,:unavailable]
	def index
		@categories = Category.includes(:items).all
    @item_order = current_order.item_orders.new if !admin
	end
  def create
    
    @item = Item.new(item_details)  
    
    # get the file_type that have been uploaded
    #raise params[:item][:image].present?.inspect
    if params[:item][:image].present?
     file_type = params[:item][:image].content_type
   # check the file type for images
     file_type == 'image/jpeg' || file_type == 'image/jpg' || file_type == 'image/png' || file_type == 'image/gif' || file_type == 'image/bmp'

      # as per the file type give the images name
      case file_type
         when "image/jpeg"
            file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.jpg"
         when "image/png"
            file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.png"
         when "image/gif"
            file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.gif"
         when "image/bmp"
            file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.bmp"
      end
        # give the file path for image
      file_path = File.join(Rails.root, 'public', 'images', 'item_images', file_name)
        # copy the image from the uploaded one to file_path
      File.open(file_path, 'wb') do |f|
            f.write params[:item][:image].read
      
      end
      @item.image = file_name
       if @item.save
          flash[:notice] = "success fully registered"
          redirect_to items_path
       else
        flash[:notice] = @item.errors.messages
         render "new"
       end   
    else 
      flash[:notice] = "please upload image"
      render "new"
    end 

  end
  def unavailable
    @item = Item.find(params[:id])
    if @item .is_available
      @item.update(is_available: false)
    else
     @item.update(is_available: true) 
    end
  end
  def new
    @item = Item.new
    @categories = Category.all
  end
  def show
    @item = Item.find(params[:id])
    @flag = ((current_order.item_orders.pluck(:item_id).include? @item.id) if current_order.item_orders.count > 0) ? 1:0 
    @item_order = current_order.item_orders.new if !admin
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item = Item.find(params[:id])
    if @item.update(item_details)
      redirect_to items_path
    else
      render "edit"
    end   
  end


  def destroy
  Item.find(params[:id]).destroy
  redirect_to items_path
 end
  private
  def item_details
   params.require(:item).permit(:name,:description,:price,:category_id)
  end 
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
     for_flash
     session[:user_id] = nil
  end
 def logincheck
   user = User.find_by_email(params[:username]) 
   unless user
      user = User.find_by_full_name(params[:username])
   end 
   if user && user.authenticate(params[:password])
     session[:user_id] = user.id
     if user.is_admin
      redirect_to items_path # need to modify
     else
      if flash[:notice]
       redirect_to new_transaction_path
      else
       reset_cart
       redirect_to items_path
      end
     end
   else 
    for_flash
   	render "login"
   end
  end 
  def logout
    if current_order.item_orders.count >0
      current_order.update(is_missed: true)
      current_user.orders << current_order
    end
    reset_session
    redirect_to root_path
  end
  private 
   def for_flash
    if flash[:notice]
     flash[:notice] = "login" 
    end 
   end
   def reset_cart
    if session[:order_id]
      if prev_order
        prev_order.item_orders.each do |prev_item_order|
          @order = current_order
          if @order.item_orders.count > 0
            if @order.item_orders.pluck(:item_id).include? prev_item_order.item_id
              item_order =  @order.item_orders.find_by_item_id(prev_item_order.item_id)
              item_order.update(quantity: item_order.quantity+1,
                         price: Item.find(prev_item_order.item_id).price*(item_order.quantity+1))
            else
            prev_item_order.update(order_id: session[:order_id])
            end
          else
            prev_item_order.update(order_id: session[:order_id])
          end 
        end
        prev_order.destroy
      end
    else
     session[:order_id] = prev_order.id if prev_order
    end
   end
   def prev_order
    current_user.orders.find_by_is_missed(true)
   end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/item_orders_helper.rb
module ItemOrdersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_delete_order.html.erb
<h6> no longer available this order </h6>

app/views/admins/_order_status_form.html.erb
<%= form_tag('/admins/order_status_update',remote: true) do %>
	<%= hidden_field_tag 'order_id',order_id %>
	<%= hidden_field_tag 'status_id',status_id %>
  <% if status_id == 2 %>
	  <%= submit_tag "paid",class: "btn btn-success btn-xs" %>
  <% elsif status_id == 3 %>
    <%= submit_tag "completed",class: "btn btn-success btn-xs" %>
  <% else %>
  	<%= submit_tag "cancel",class: "btn btn-danger btn-xs" %>
  <% end %>
<%end%>

app/views/admins/_single_order.html.erb
<% if status.orders.count > 0 %>
	<div class="row">
	  <div class=" pull-left">
	   <input type="search" id="search" value="" class="form-control" placeholder="Search by orders">
	  </div>
	  <div class="message"></div>
	</div>
	<div class="row" style="margin-top: 10px;">
	  <div class="col-lg-12">
	    <table class="table" id="table">
	      <thead>
	        <tr>
	          <th class="text-center">Order-id:</th>
	          <th class="text-center">User</th>
	          <th class="text-center">staus</th>
	          <th class="text-center">Placed_at/updated_at</th>
	          <th class="text-center">Action</th>
	        </tr>
	      </thead>
	      <tbody>  
		      <% status.orders.each do |order| %>
			      <% if order.user %>
			        <tr>
			          <td class="text-center" id = "single_order_<%=order.id%>"><%=order.id%></td>
			          <td class="text-center"><%=order.user.email%></td>
			          <td class="text-center"><%=order.status.name%></td>
			          <td class="text-center"><%=time_ago_in_words(order.updated_at)%></td>
			          <% if status.name == "ordered" %>
			          	<td class="text-center" > 
			          		<%= render "order_status_form",order_id: order.id,status_id: 2 %>
			          		<%= render "order_status_form",order_id: order.id,status_id: 4 %>
			          		<%=link_to "details",details_path(order.id),class: "btn btn-info btn-xs"%>  
			          	</td>
			          <% elsif status.name == "paid" %>
			          	<td class="text-center"> 
			          		<%= render "order_status_form",order_id: order.id,status_id: 3 %>
			          		<%= render "order_status_form",order_id: order.id,status_id: 4 %>  
			          	  <%=link_to "details",details_path(order.id),class: "btn btn-info btn-xs"%>
			          	</td>
			          <% else %>
			          	<td class = "text-center">
			          		<%=link_to "details",details_path(order.id),class: "btn btn-info btn-xs"%>
			          	</td>
			          <% end %>
			        </tr>
			      <% end %>
		      <% end %>
	      </tbody>
	    </table>
	  </div>
	</div>
<% else %>
 <center> <h6>no orders under this status</h6> </center>
<% end %>

app/views/admins/_unknown_order.html.erb
<% if @unknown_orders %>
  <div class="row">
    <div class="pull-left">
     <input type="search" id="search" value="" class="form-control" placeholder="Search by orders">
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <table class="table" id="table">
        <thead>
          <tr>
            <th class="text-center">Order-id:</th>
            <th class="text-center">Placed_at/updated_at</th>
            <th class="text-center">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @unknown_orders.each do |order| %>
            <tr >
              <td class="text-center" id="unknown_order_<%=order.id%>"><%=order.id%></td>
              <td class="text-center" id="unknown_order_<%=order.id%>"><%=time_ago_in_words(order.updated_at)%></td>
              <td class="text-center" id="unknown_order_<%=order.id%>"><%=link_to "delete",delete_order_path(order.id),class: "btn btn-danger btn-xs",remote: true%></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
 <center> <h6>no orders under this status</h6> </center>
<% end %>

app/views/admins/_unkown_order.html.erb
<h6>hai</h6>

app/views/admins/delete_order.js.erb
$("#unknown_order_<%=@id%>").parent()
.replaceWith("<tr><td class = 'text-center' colspan='3'>no longer available this order <%=@id%></td></tr>");

app/views/admins/details.html.erb
<style type="text/css">
.content {
	padding: 30px;
	background: #f1f3fa;
}

.margin-bottom-30 {
	margin-bottom: 30px;
}

/* Portlet */
.portlet {
	background: #fff;
	padding: 20px;
}

.portlet.portlet-gray {
	background: #f7f7f7;
}

.portlet.portlet-bordered {
	border: 1px solid #eee;
}

/* Portlet Title */
.portlet-title {
	padding: 0;
  	min-height: 40px;
  	border-bottom: 1px solid #eee;
  	margin-bottom: 18px;
}

.caption {
	float: left;
	display: inline-block;
	font-size: 18px;
	line-height: 18px;
}
.caption i {
	color: #777;
	font-size: 15px;
	font-weight: 300;
	margin-top: 3px;
}

.caption-subject {
	color: #666;
	font-size: 16px;
	font-weight: 600;
}

.caption-helper {
	padding: 0;
	margin: 0;
	line-height: 13px;
	color: #9eacb4;
	font-size: 13px;
	font-weight: 400;
}

</style>
<div class="content">
	<div class = "container">
		<div class="col-md-6 margin-bottom-30">
			<div class="portlet">
				<div class="portlet-title">
					<div class="caption">
						<i class="fa fa-bars"></i>
						<span class="caption-subject text-uppercase"> Order - <%=@order.id%></span>
						<span class="caption-helper">order full details...</span>
					</div>
				</div>
				<div class="portlet-body">
					<h6>placed_at: <%=@order.updated_at.in_time_zone("New Delhi").strftime("%I:%M %p %^b %Y")%>  (<%=time_ago_in_words(@order.updated_at)%> ago ) </h6>
					<h6>purchaser Name: <%=@order.user.full_name%> (<%=@order.user.email%>)</h6>
          <div class="table">
            <h6>items ordered:</h6>
          	<table class="table" style="border: 1px solid">
          		<thead>
          			<th>item</th>
          			<th>quantity</th>
          			<th>price</th>
          			<th>subtotal</th>
          		</thead>
          		<tbody>
          			<%@order.item_orders.each do |item_order| %>
          				<tr>
          					<td class="text-center"><%=link_to "#{item_order.item.name}",item_path(item_order.item.id)%></td>
          					<td class="text-center"><%=item_order.quantity%></td>
          					<td class="text-center"><%=item_order.item.price%></td>
          					<td class="text-center"><%=item_order.price%></td>
          				</tr>
          			<% end %>
          		</tbody>
          	</table>
          </div>
          <div class="pull-left">Total: <i class = "fa fa-inr"></i> <%=@cost%></div>
          <div class="pull-right">Status: <b><%=@order.status.name%></b></div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/admins/new.html.erb
	<div class = "container well " style = "width:500px">
	 <% if flash[:notice] %>
	    <div class="notice"><%= flash[:notice] %></div>
	  <% end %>
	 <h2> admin registration page </h2>
	 <%= form_for(@admin, url: admins_path) do |f| %>
	 adminname: <%= f.text_field :full_name,placeholder: "enter user name",class: "form form-control",required: true%>
	 displayname: <%= f.text_field :display_name,placeholder: "enter display name",class: "form form-control"%><span>optional</span><br>
	 email: <%= f.email_field :email,placeholder: "enter email",class: "form form-control",required: true%>
	 password: <%= f.password_field :password,placeholder: "enter password",class: "form form-control",required: true %>
	 confirm password<%= f.password_field :password_confirmation,placeholder: "reenter password ",class: "form form-control",required: true %><br>
	 image: <%= f.file_field :image%><br>
	 <%=f.submit "register" %>
	 <%end%>
	</div>

app/views/admins/order_status_update.js.erb
$("#single_order_<%=@order.id%>").parent()
.replaceWith("<tr><td class = 'text-center' colspan='5'>  order <%=@order.id%> moved to <%=@order.status.name%></td></tr>");

app/views/admins/orders.html.erb
<style type="text/css">
  .tabbable-panel {
    border:2px solid #337ab7 ;

    padding: 10px;

  }
  .table {
    border:2px solid #337ab7 ;    
  }
  .tabbable-line > .nav-tabs {
    border: 0;
    margin: 0px;
  }
  .tabbable-line > .nav-tabs > li {
    margin-right: 2px;
  }
  .tabbable-line > .nav-tabs > li > a {
    border: 0;
    margin-right: 0;
    color: #737373;
  }
  .tabbable-line > .nav-tabs > li > a > i {
    color: #a6a6a6;
  }
  .tabbable-line > .nav-tabs > li.open, .tabbable-line > .nav-tabs > li:hover {
    border-bottom: 4px solid #fbcdcf;
  }
  .tabbable-line > .nav-tabs > li.open > a, .tabbable-line > .nav-tabs > li:hover > a {
    border: 0;
    background: none !important;
    color: #333333;
  }
  .tabbable-line > .nav-tabs > li.open > a > i, .tabbable-line > .nav-tabs > li:hover > a > i {
    color: #a6a6a6;
  }
  .tabbable-line > .nav-tabs > li.open .dropdown-menu, .tabbable-line > .nav-tabs > li:hover .dropdown-menu {
    margin-top: 0px;
  }
  .tabbable-line > .nav-tabs > li.active {
    border-bottom: 4px solid #f3565d;
    position: relative;
  }
  .tabbable-line > .nav-tabs > li.active > a {
    border: 0;
    color: #337ab7;
  }
  .tabbable-line > .nav-tabs > li.active > a > i {
    color: #337ab7;
  }
  .tabbable-line > .tab-content {
    margin-top: -3px;
    background-color: #fff;
    border: 0;
    border-top: 1px solid #eee;
    padding: 15px 0;
  }
  .portlet .tabbable-line > .tab-content {
    padding-bottom: 0;
  }
  .btn {
    display: inline;
  }
  @media (max-width: 1500px) {
    .item_index {
      width: 1000px;

      top : 50px;
    }
  }
  
</style>
<script type="text/javascript">
  $(function () {
    $( '.table' ).searchable({
        striped: true,
        oddRow: { 'background-color': '#f5f5f5' },
        evenRow: { 'background-color': '#fff' },
        searchType: 'fuzzy'
    });
    var lastTab = localStorage.getItem('lastTab');
    if (lastTab) {
        $('[href="' + lastTab + '"]').tab('show');
    }

    $(".order_nav a").click(function() {
       localStorage.setItem('lastTab', $(this).attr('href'));
       location.reload();
    });
});
</script>

<div class="container item_index">
  <div class="row">
    <div class="col-md-12">
      <h3>orders</h3>
      <div class="tabbable-panel">
        <div class="tabbable-line">
          <ul class="nav nav-tabs order_nav">
            <% @statuses.each_with_index do |status,i| %>
              <% if i == 0 %>
                <li class="active">
                  <a href = "#tab_default_<%=status.id%>" data-toggle="tab">
                    <%=status.name%>
                  </a>
                </li>
              <% else %>
                <li>
                  <a href = "#tab_default_<%=status.id%>" data-toggle="tab">
                    <%=status.name%>
                  </a>
                </li>
              <% end %>    
            <% end %>
            <li>
              <a href = "#tab_default_unknown" data-toggle="tab">
                unknown
              </a>
            </li>
          </ul>
          <div class="tab-content">
            <% @statuses.each_with_index do |status,i| %>
              <% if i == 0 %>
                <div class="tab-pane active fade in" id="tab_default_<%=status.id%>">
                  <%= render "single_order",status: status%>
                </div> 
              <% else %>    
                <div class="tab-pane fade" id="tab_default_<%=status.id%>">
                  <%= render "single_order",status: status%>
                </div> 
              <% end %>
            <% end %>
            <div class="tab-pane fade" id="tab_default_unknown">
              <%= render "unknown_order" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
  <title>DinnerDash</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
  <script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->


</head>
<body style="background: #f1f3fa;">
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Dinner dash</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
         
            <% if current_user %>
              <li>  <%= link_to "Sign out", signout_path%></li>
            <% else %>
              <li> <%= link_to "Sign in", login_page_path%>  </li>
            <% end %>
          
          
            <% if !current_user %>
             <li> <%= link_to "signup", signup_path %></li>  
            <% end %>
          
         <% if current_user %>
          <% if current_user.is_admin? %>
            <li><a href="/admins/orders">manage orders</a></li>
            <li><a href="/items">manege items</a></li>
          <% else %>
            <li><a href="/items">items</a></li>
            <li><a href="/cart/index">cart <span class="badge"><%= current_order_items %></span></a></li>
         <% end %>  
        <%end%> 
        <%if !current_user %>
         <li><a href="/items">items</a></li>
         <li><a href="/cart/index">cart <span class="badge"><%= current_order_items %></span></a></li>
        <% end %> 
          
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav><!-- /.navbar -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <div class="nav-side-menu fixed-top ">
        <div class="brand"><% if current_user %>
            <h4><%= current_user.full_name %></h4>  
          <% else %>
            Guest
          <% end %></div>
        <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
      
            <div class="menu-list">
      
                <ul id="menu-content" class="menu-content collapse out">    
                  <% if current_user %>
                    <% if current_user.is_admin? %>
                      <li>
                       <a href="/">
                        <i class="fa fa-dashboard fa-lg"></i> Dashboard
                       </a>
                      </li>
                      <li><a href="/users"><i class="fa fa-users fa-lg"></i> manage users</a></li>
                      <li><a href="/categories/index"><i class="fa fa-th-large fa-lg"></i>manage categories</a></li>
                    <%else%>
                      <li>
                       <a href="/">
                        <i class="fa fa-dashboard fa-lg"></i> Dashboard
                       </a>
                      </li>
                      <li><a href="/users/pastorders"><i class="fa fa-history fa-lg"></i>  your's orders</a></li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user fa-lg"></i> Profile
                        </a>
                      </li>
                    <%end%> 
                    
                  <%end%> 
                </ul>
         </div>
  </div>      
  <div class = "page-content" style="background: #f1f3fa;">
    <%= yield %>
  </div>
  <div class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container">
      <p class="navbar-text pull-left">© 2015 - Site Built By santosh kumar </p>
    </div>
  </div>
</body>
</html>