config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'

   root 'items#index'
   get 'login/login' =>'login#login',as: :login_page
   post 'login/logincheck' => 'login#logincheck' ,as: :login_logincheck
   get 'login/logout' => 'login#logout',as: :signout
   
   
   get 'users/new' => 'users#new', as: :signup
   post 'users/create' => 'users#create', as: :users
   get 'users' => 'users#index',as: :all_users
   get 'users/pastorders' => 'users#pastorders',as: :pastorders
   get 'users/missedorders' => 'users#missedorders',as: :missedorders
   
   get 'admins/new' => 'admins#new', as: :adminsignup
   post 'admins/create' => 'admins#create', as: :admins
   get 'admins/orders' => 'admins#orders', as: :orders
   get 'admins/details/:id' => 'admins#details',as: :details

   get 'admins/delete_order/:id'=> 'admins#delete_order',as: :delete_order

   post 'admins/order_status_update' => 'admins#order_status_update',as: :order_status_update
   
    get 'categories/index' => 'categories#index',as: :allcategories
    get 'categories/new' => 'categories#new',as: :newcategory
    post 'categories/create' => 'categories#create',as: :categories
    get 'categories/destroy/:id'=> 'categories#destroy',as: :deletecategory
    get 'categories/:id' => 'categories#show' , as: :show_category
    resources :items
    get 'items/unavailable/:id'=> 'items#unavailable',as: :unavailableitem 
      
    resources :item_orders
    get 'cart/index' => "cart#index", as: :cart
    get 'cart/clear_cart' => "cart#clear_cart",as: :clear_cart
    

    resources :transactions ,only: [:new,:create]

end

app/models/item.rb
class Item < ActiveRecord::Base
  validates :name, :description, :price, :image, :category_id ,presence: true
  has_many :item_orders,dependent: :destroy
  has_many :orders,:through => :Item,dependent: :destroy
  belongs_to :category
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :auth_admin, only: [:new,:create,:edit,:update,:destroy,:unavailable]
	def index
		@categories = Category.includes(:items).all
    @item_order = current_order.item_orders.new if !admin
	end
  def create
    
    @item = Item.new(item_details)  
    
    # get the file_type that have been uploaded
    #raise params[:item][:image].present?.inspect
    if params[:item][:image].present?
     file_type = params[:item][:image].content_type
   # check the file type for images
     file_type == 'image/jpeg' || file_type == 'image/jpg' || file_type == 'image/png' || file_type == 'image/gif' || file_type == 'image/bmp'

      # as per the file type give the images name
      case file_type
         when "image/jpeg"
            file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.jpg"
         when "image/png"
            file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.png"
         when "image/gif"
            file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.gif"
         when "image/bmp"
            file_name = "pic_#{Time.now.strftime("%Y%m%d%H%M%S")}.bmp"
      end
        # give the file path for image
      file_path = File.join(Rails.root, 'public', 'images', 'item_images', file_name)
        # copy the image from the uploaded one to file_path
      File.open(file_path, 'wb') do |f|
            f.write params[:item][:image].read
      
      end
      @item.image = file_name
       if @item.save
          flash[:notice] = "success fully registered"
          redirect_to items_path
       else
        flash[:notice] = @item.errors.messages
         render "new"
       end   
    else 
      flash[:notice] = "please upload image"
      render "new"
    end 

  end
  def unavailable
    @item = Item.find(params[:id])
    if @item .is_available
      @item.update(is_available: false)
    else
     @item.update(is_available: true) 
    end
  end
  def new
    @item = Item.new
    @categories = Category.all
  end
  def show
    @item = Item.find(params[:id])
    @flag = ((current_order.item_orders.pluck(:item_id).include? @item.id) if current_order.item_orders.count > 0) ? 1:0 
    @item_order = current_order.item_orders.new if !admin
  end
  def edit
    @item = Item.find(params[:id])
  end
  def update
    @item = Item.find(params[:id])
    if @item.update(item_details)
      redirect_to items_path
    else
      render "edit"
    end   
  end


  def destroy
  Item.find(params[:id]).destroy
  redirect_to items_path
 end
  private
  def item_details
   params.require(:item).permit(:name,:description,:price,:category_id)
  end 
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_add_to_cart_form.html.erb
<%= form_for @item_order, remote: true do |f| %>
<div class="input-group">
	<div class="input-group-btn">
		<%= f.hidden_field :item_id, value: item.id %>
		<%= f.hidden_field :quantity, value: 1%>
		<%= f.hidden_field :price, value: item.price %>
		<%= f.submit "Add to Cart", class: "btn btn-primary" %>
	</div>
</div>
<% end %>

app/views/items/_admin_item.html.erb
<tr>
  <% var_img = "item_images/#{item.image}" %>
  <td><%= image_tag var_img, :height => '140px', :width => '185px' %></td>
  <td><strong><%=item.name%></strong><hr><%= item.description%></td>
  <td><i class = "fa fa-rupee"><%=item.price%></i></td>
  <td><%=link_to "edit",edit_item_path(item.id),class: "btn btn-sm btn-primary"%>
    <% if item.is_available %>
    <div class="un<%=item.id%>"><%=link_to "make it unavailable",unavailableitem_path(item.id),class: "btn btn-sm btn-info", remote: true%></div>
    <% else %>
    <div class="un<%=item.id%>"><%=link_to "make it available",unavailableitem_path(item.id),class: "btn btn-sm btn-info",remote: true%></div>
    <% end %>
    <%= link_to "delete",item_path(item.id),method: :delete,data: {confirm: 'Are you sure? your admin' },class: "btn btn-sm btn-danger" %>  
  </td>
</tr>

app/views/items/_available.html.erb
<% if @item.is_available %>
 <%=link_to "make it unavailable",unavailableitem_path(@item.id),class: "btn btn-sm btn-info", remote: true%>
<% else %>
 <%=link_to "make it available",unavailableitem_path(@item.id),class: "btn btn-sm btn-info",remote: true%>
<% end %> 

app/views/items/_buttons.html.erb
<div class="buttons" style="margin-right: 5px">
 <%= link_to "checkout", cart_path, class: "btn btn-success btn-xl"%>
 <%= link_to "continue order", items_path , class: "btn btn-success btn-xl"%>
 <%= link_to "previous orders", pastorders_path, class: "btn btn-success btn-xl" %>
</div>

app/views/items/_item.html.erb
  <table class="table table-hover" id="dev-table">
    <thead>
      <tr>
        <th>item</th>
        <th>About item</th>
        <th>price</th>
        <th>action</th>
      </tr>
    </thead>
    <tbody>
      <% category.items.each do |item| %>
      <% if current_user %>
      <% if current_user.is_admin %>
      <%= render "admin_item" ,item: item %>
      <% else %>
      <%= render "user_item" , item: item%>
      <% end %>    
      <%elsif%>
      <tr>
        <%= render "user_item",item: item %>
      </tr>
      <%end%> 
      <%end%>     
    </tbody>
  </table>

app/views/items/_user_item.html.erb
<tr>
  <% var_img = "item_images/#{item.image}" %>
  <td><%= image_tag var_img, :height => '140px', :width => '185px' %></td>
  <td><strong><%=item.name%></strong><hr><%= item.description%></td>
  <td><i class = "fa fa-rupee"><%=item.price%></i></td>
  <td>
    <%= form_for @item_order, remote: true do |f| %>
    <div class="input-group">
      <div class="input-group-btn">
        <%= f.hidden_field :item_id, value: item.id %>
        <%= f.hidden_field :quantity, value: 1%>
        <%= f.hidden_field :price, value: item.price %>
        <%= f.submit "Add to Cart", class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </td>
</tr>

app/views/items/edit.html.erb
<div class = "container well" style = "width:500px">
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
  <h2> edit item </h2>
 <%= form_for @item do |f| %>
  item name:  <%= f.text_field "name",placeholder: "enter item name",class: "form form-control",required: true%><br>
  item description: <%= f.text_area "description",placeholder: "enter about item",class: "form form-control",required: true%><br>
  item price:<%= f.number_field "price",placeholder: "enter price ",class: "form form-control",required: true%><br>
  select category: <%= f.collection_select "category_id",Category.all, :id,:name%><br>
  <%= f.submit "update item",class: "btn btn-success"%><br>
 <%end%>
</div>

app/views/items/index.html.erb
<style type="text/css">
  .tabbable-panel {
    border:2px solid #337ab7 ;

    padding: 10px;

  }
  .tabbable-line > .nav-tabs {
    border: 0;
    margin: 0px;
  }
  .tabbable-line > .nav-tabs > li {
    margin-right: 2px;
  }
  .tabbable-line > .nav-tabs > li > a {
    border: 0;
    margin-right: 0;
    color: #737373;
  }
  .tabbable-line > .nav-tabs > li > a > i {
    color: #a6a6a6;
  }
  .tabbable-line > .nav-tabs > li.open, .tabbable-line > .nav-tabs > li:hover {
    border-bottom: 4px solid #fbcdcf;
  }
  .tabbable-line > .nav-tabs > li.open > a, .tabbable-line > .nav-tabs > li:hover > a {
    border: 0;
    background: none !important;
    color: #333333;
  }
  .tabbable-line > .nav-tabs > li.open > a > i, .tabbable-line > .nav-tabs > li:hover > a > i {
    color: #a6a6a6;
  }
  .tabbable-line > .nav-tabs > li.open .dropdown-menu, .tabbable-line > .nav-tabs > li:hover .dropdown-menu {
    margin-top: 0px;
  }
  .tabbable-line > .nav-tabs > li.active {
    border-bottom: 4px solid #f3565d;
    position: relative;
  }
  .tabbable-line > .nav-tabs > li.active > a {
    border: 0;
    color: #337ab7;
  }
  .tabbable-line > .nav-tabs > li.active > a > i {
    color: #337ab7;
  }
  .tabbable-line > .tab-content {
    margin-top: -3px;
    background-color: #fff;
    border: 0;
    border-top: 1px solid #eee;
    padding: 15px 0;
  }
  .portlet .tabbable-line > .tab-content {
    padding-bottom: 0;
  }
  @media (max-width: 1500px) {
    .item_index {
      width: 1000px;

      top : 50px;
    }
  }
  
</style>

<div class="container item_index">
  <div class="row">
    <div class="col-md-12">
      <h3>Items 
        <% if current_user %> 
        <% if current_user.is_admin %>  
        <a href="items/new" class="pull-right"><button class = "btn btn-primary">ADD<i class="fa fa-plus-circle fa-lg"></i></button></a>
        <% end %>
        <% end %>
      </h3>
      <div class="tabbable-panel">
        <div class="tabbable-line">
          <ul class="nav nav-tabs item_nav">
            <% @categories.each_with_index do |category,i| %>
              <% if i == 0 %>
                <li class="active">
                  <a href = "#tab_default_<%=category.id%>" data-toggle="tab">
                    <%=category.name%>
                  </a>
                </li>
              <% else %>
                <li>
                  <a href = "#tab_default_<%=category.id%>" data-toggle="tab">
                    <%=category.name%>
                  </a>
                </li>
              <% end %>    
            <% end %>
          </ul>
          <div class="tab-content">
            <% @categories.each_with_index do |category,i| %>
              <% if i == 0 %>
                <div class="tab-pane active fade in" id="tab_default_<%=category.id%>">
                  <%= render "item",category: category%>
                </div> 
              <% else %>    
                <div class="tab-pane fade" id="tab_default_<%=category.id%>">
                  <%= render "item",category: category%>
                </div> 
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  

app/views/items/new.html.erb
<div class="container">
	<div class="row">
		<%= form_for @item , :html => {class: 'form-horizental'} do |f| %>
		<fieldset>
			<!-- Form Name -->
			<legend>::: Item Creation</legend>
			<!-- Text input-->
			<div class="control-group">
				<label class="control-label" for="full_name">Item Name</label>
				<div class="controls">
					<%= f.text_field "name",placeholder: "enter item name",class: "form form-control",required: true%><br>
				</div>
			</div>

			<!-- Text input-->
			<div class="control-group">
				<label class="control-label" for="father_name">Description</label>
				<div class="controls">
					<%= f.text_area "description",placeholder: "enter about item",class: "form form-control",required: true%><br>
				</div>
			</div>

			<!-- Text input-->
			<div class="control-group">
				<label class="control-label" for="mother_name">Price</label>
				<div class="controls">
					<%= f.number_field "price",placeholder: "enter price ",class: "form form-control",required: true%><br>
				</div>
			</div>

			<!-- Text input-->
			<div class="control-group">
				<label class="control-label" for="email">category</label>
				<div class="controls">
					<%= f.collection_select "category_id",Category.all, :id,:name%><br>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="photo">Photo</label>
				<div class="controls">
					<%= f.file_field "image" %><br>
				</div>
			</div>

			<!-- Button -->
			<div class="control-group">
				<label class="control-label" for="submit"></label>
				<div class="controls">
					<%= f.submit "add item",class: "btn btn-success"%><br>
				</div>
			</div>
			</fieldset>
			<%end%>

		

	</div>
</div>

app/views/items/show.html.erb
<style type="text/css">
.item{
  margin-top: 40px;
}
.coupon {
    border: 3px dashed #bcbcbc;
    border-radius: 10px;
    font-family: "HelveticaNeue-Light", "Helvetica Neue Light", 
    "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
    font-weight: 300;
}
.coupon #head {
    border-top-left-radius: 10px;
    border-top-right-radius: 10px;
    min-height: 56px;
}

.coupon #footer {
    border-bottom-left-radius: 10px;
    border-bottom-right-radius: 10px;
}

#title .visible-xs {
    font-size: 12px;
}

.coupon #title img {
    font-size: 30px;
    height: 30px;
    margin-top: 5px;
}

@media screen and (max-width: 500px) {
    .coupon #title img {
        height: 15px;
    }
}

.coupon #title span {
    float: right;
    margin-top: 5px;
    font-weight: 700;
    text-transform: uppercase;
}

.coupon-img {
    width: 100%;
    margin-bottom: 15px;
    padding: 0;
}

.items {
    margin: 15px 0;
}

.usd, .cents {
    font-size: 20px;
}

.number {
    font-size: 40px;
    font-weight: 700;
}

sup {
    top: -15px;
}

.disclosure {
    padding-top: 15px;
    font-size: 14px;
    text-align: center;
}

.coupon-code {
    color: #333333;
    font-size: 11px;
}

</style>
<div class="container item">
  <div class="row">
  	<div class="col-md-6 col-md-offset-3">
  		<div class="panel panel-default coupon">
  			<div class="panel-heading" id="head">
  				<div class="panel-title" id="title">
  					<span> Dinner Dash </span>
  					<span class="hidden-xs pull-left"><%=@item.name%></span>
  					<span class="visible-xs pull-left"><%=@item.name%></span>
  				</div>
  			</div>
  			<div class="panel-body">
          <% var_img = "item_images/#{@item.image}" %>
          <%= image_tag var_img,:height => '280px', :width => '185px', class: "coupon-img img-rounded" %>
          <div class="col-md-3">
           <div class="offer">
            <span class="fa fa-inr"><%=@item.price%></span>
           </div>
          </div>
          <div class="col-md-12">
           <p class="disclosure">
            <%=@item.description%>
           </p>
          </div>
        </div>
        <div class="panel-footer">
          <% if @flag == 0 %>
            <% if @item.is_available %>
              <div class="coupon-code text-center">
                <%= form_for @item_order,remote: true do |f| %>
                  <div class="input-group">
                    <div class="input-group-btn">
                      <% flash[:action] = "show" %>
                      <%= f.hidden_field :item_id, value: @item.id %>
                      <%= f.hidden_field :quantity, value: 1%>
                      <%= f.hidden_field :price, value: @item.price %>
                      <%= f.submit "Add to Cart", class: "btn btn-primary" %>
                    </div>
                  </div>
                <% end %>  
              </div>
            <% else %>
              <div class="text-center" style="color:red">
                out of stock
              </div>
            <% end -%>
          <%else%>
           <div class="text-center">
            <%= render 'buttons'%>
           </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/unavailable.js.erb
$('.un<%=@item.id%>').html('<%= j render "available"%>')