config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'

   root 'items#index'
   get 'login/login' =>'login#login',as: :login_page
   post 'login/logincheck' => 'login#logincheck' ,as: :login_logincheck
   get 'login/logout' => 'login#logout',as: :signout
   
   
   get 'users/new' => 'users#new', as: :signup
   post 'users/create' => 'users#create', as: :users
   get 'users' => 'users#index',as: :all_users
   get 'users/pastorders' => 'users#pastorders',as: :pastorders
   get 'users/missedorders' => 'users#missedorders',as: :missedorders
   
   get 'admins/new' => 'admins#new', as: :adminsignup
   post 'admins/create' => 'admins#create', as: :admins
   get 'admins/orders' => 'admins#orders', as: :orders
   get 'admins/details/:id' => 'admins#details',as: :details

   get 'admins/delete_order/:id'=> 'admins#delete_order',as: :delete_order

   post 'admins/order_status_update' => 'admins#order_status_update',as: :order_status_update
   
    get 'categories/index' => 'categories#index',as: :allcategories
    get 'categories/new' => 'categories#new',as: :newcategory
    post 'categories/create' => 'categories#create',as: :categories
    get 'categories/destroy/:id'=> 'categories#destroy',as: :deletecategory
    get 'categories/:id' => 'categories#show' , as: :show_category
    resources :items
    get 'items/unavailable/:id'=> 'items#unavailable',as: :unavailableitem 
      
    resources :item_orders
    get 'cart/index' => "cart#index", as: :cart
    get 'cart/clear_cart' => "cart#clear_cart",as: :clear_cart
    

    resources :transactions ,only: [:new,:create]

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :items, dependent: :destroy
validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
 def index
 	@categories = Category.all
 end
 def new
 	@category = Category.new
 end
 
 def show
  @category = Category.includes(:items).find(params[:id])
 end

 def create 
 	@category = Category.new(name: params[:category][:name])
 	if @category.save
 		redirect_to allcategories_path
 	else
 		@categories = Category.all
 	 render "index"
 	end	
 end
 def destroy
  Category.find(params[:id]).destroy
  redirect_to allcategories_path
 end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_new.html.erb
<%= form_for @category do |f| %>
  category name<%= f.text_field :name,placeholder:"enter category name",class: "form form-control" %>
  <%= f.submit "add category",class: "btn btn-success btn-sm" %>
<%end%>

app/views/categories/index.html.erb
<div class="container" style="margin-top:20px;">
  <div class="row">
    <div class="col-xs-6">
        <h3 class="text-center">categories</h3>
          <div class="well">
            <ul class="list-group checked-list-box">
              <div id="new"></div><br>
              <% @categories.each do |category| %>
                <li class="list-group-item"><%=category.name%>
                  <div class="pull-right"><%=link_to "delete",deletecategory_path(category.id),data: { confirm: 'Are you sure? your a admin' } %></div>
                </li>
              <%end%><br>
              <%=link_to "Add",newcategory_path,class: "btn btn-success btn-sm",remote: true%>
            </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container well " style = "width:500px">
 <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
 <%= form_for @category do |f| %>
  category name<%= f.text_field :name,placeholder:"enter category name",class: "form form-control" %>
  <%= f.submit "add category",class: "btn btn-success" %>
 <%end%>
</div>

app/views/categories/new.js.erb
$("#new").html('<%= j render "new"%>')