config/routes.rb
Rails.application.routes.draw do
  get 'transactions/new'

   root 'items#index'
   get 'login/login' =>'login#login',as: :login_page
   post 'login/logincheck' => 'login#logincheck' ,as: :login_logincheck
   get 'login/logout' => 'login#logout',as: :signout
   
   
   get 'users/new' => 'users#new', as: :signup
   post 'users/create' => 'users#create', as: :users
   get 'users' => 'users#index',as: :all_users
   get 'users/pastorders' => 'users#pastorders',as: :pastorders
   get 'users/missedorders' => 'users#missedorders',as: :missedorders
   
   get 'admins/new' => 'admins#new', as: :adminsignup
   post 'admins/create' => 'admins#create', as: :admins
   get 'admins/orders' => 'admins#orders', as: :orders
   get 'admins/details/:id' => 'admins#details',as: :details

   get 'admins/delete_order/:id'=> 'admins#delete_order',as: :delete_order

   post 'admins/order_status_update' => 'admins#order_status_update',as: :order_status_update
   
    get 'categories/index' => 'categories#index',as: :allcategories
    get 'categories/new' => 'categories#new',as: :newcategory
    post 'categories/create' => 'categories#create',as: :categories
    get 'categories/destroy/:id'=> 'categories#destroy',as: :deletecategory
    get 'categories/:id' => 'categories#show' , as: :show_category
    resources :items
    get 'items/unavailable/:id'=> 'items#unavailable',as: :unavailableitem 
      
    resources :item_orders
    get 'cart/index' => "cart#index", as: :cart
    get 'cart/clear_cart' => "cart#clear_cart",as: :clear_cart
    

    resources :transactions ,only: [:new,:create]

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	def new
		if session[:user_id]
 	   gon.client_token = generate_client_token
			@sum = sum(current_order.id)
 	  else	
     flash[:notice] = "login from controller"
     redirect_to login_page_path
    end
  end
		def create
			unless current_user.has_payment_info?
				
				@result = Braintree::Transaction.sale(
					amount: sum(current_order.id),
					payment_method_nonce: params[:payment_method_nonce],
					customer: {
						first_name: params[:first_name],
						last_name: params[:last_name],
						company: params[:company],
						email: current_user.email,
						phone: params[:phone]
						},
						options: {
							store_in_vault: true
							})
			else
				
				@result = Braintree::Transaction.sale(
					amount: sum(current_order.id),
					payment_method_nonce: params[:payment_method_nonce])
			end

			if @result.success?
				current_user.update(braintree_customer_id: @result.transaction.customer_details.id) unless current_user.has_payment_info?
				current_user.orders << current_order
				current_order.update(total_cost: sum(current_order.id),is_missed: false,status_id: 2)
				redirect_to clear_cart_path, notice: "Congraulations! Your transaction has been successfully!"

			else
				flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
				gon.client_token = generate_client_token
				render :new
			end
		end

		private
		def generate_client_token
			if current_user.has_payment_info?
				Braintree::ClientToken.generate(customer_id: current_user.braintree_customer_id)
			else
				Braintree::ClientToken.generate
			end
		end
		
	end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/new.html.erb
<div class ="row container" style = "margin-left: 300px;">
	<div class = "col-md-6">
		<div class="form-container  radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
			<h2 class="mbs">New Transaction</h2>
			<%= form_tag transactions_path do%>
			<p>Please enter your payment details:</p>
			<div id="dropin"></div>
			<%=submit_tag "Pay #{@sum}$", class: "button btn btn-success" %>
			<%end%>
		</div>

		<p>Please enter your personal info:</p>
		<div class="mb1">
			<%= text_field_tag :first_name, "",placeholder: "First Name", class: "radius" %>
		</div>
		<div class="mb1">
			<%= text_field_tag :last_name, "",placeholder: "Last Name", class: "radius" %>
		</div>
		<div class="mb1">
			<%= text_field_tag :company, "",placeholder: "Company", class: "radius" %>
		</div>
		<div class="mb1">
			<%= text_field_tag :phone, "",placeholder: "Phone", class: "radius" %>
		</div>
	</div>
</div>